# Generated by Django 5.2.4 on 2025-07-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='available_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='available_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
    ]
