# Generated by Django 5.2.4 on 2025-07-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_resources_available_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(related_name='resources', to='app.resources'),
        ),
    ]
