# Generated by Django 5.2.4 on 2025-07-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='resources',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(default='system', max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('matching_skills', models.ManyToManyField(related_name='assignments', to='app.skill')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.resources')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.task')),
            ],
            options={
                'unique_together': {('task', 'resource')},
            },
        ),
    ]
