# Generated by Django 5.2.4 on 2025-07-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_task_resources_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_by',
        ),
    ]
