# Generated by Django 5.2.4 on 2025-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_assignment_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_skill_covered',
            field=models.FloatField(default=0.0),
        ),
    ]
